### ISSUE TITLE
Face Recognition on Jetson Xavier

### ISSUE THREAD

**Issue by EmilianoHFlores** [RoBorregos/robocup-home-vision#1]
Solve dlib's performance issue on [Jetson Xavier's ARM64 architecture](https://forums.developer.nvidia.com/t/issue-installing-dlib-on-jetson-agx-xavier/111635/6), integrate person recognition and follower on the robot. Include Dockerfile and/or documentation.

**Comment by Ale-Coeto** [comment]
Install on jetson
``` bash
wget http://dlib.net/files/dlib-19.17.tar.bz2
tar jxvf dlib-19.17.tar.bz2

cd dlib-19.17/
mkdir build
cd build/
cmake ..
cmake --build .
$ cd ../
$ sudo python3 setup.py install
```

**Comment by Ale-Coeto** [comment]
Didn't work with docker

**Comment by Ale-Coeto** [comment]
https://gist.github.com/dagsonpatrick/759a3096064bf1a475969ea59e4c5edd
