### ISSUE TITLE
Person Tracking for Navigation Tasks

### ISSUE THREAD

**Issue by EmilianoHFlores** [RoBorregos/robocup-home-vision#2]
Create a ROS Node(s) to run a person detection+tracking. Further development expects including a ReID model.

**Comment by Ale-Coeto** [comment]
Development of ROS Node using yolov8n with bytetrack to detect and track people. Implementation of ft_net_dense Re-Identification model and mediapipe pose detector to improve performance.

ReId model (Trained with Duke Data Set): [Person_reID_baseline_pytorch](https://github.com/layumi/Person_reID_baseline_pytorch)
